services:

  redis:
    container_name: redis_advanced
    image: redis:latest

    restart: always

    command: redis-server --save 60 1

  backend:
    build: .
    container_name: backend

    depends_on:
      - redis

    environment:
      - SECRET_KEY=test
      - DEBUG=False
    ports:
      - "8001:8000"

    command: python -m gunicorn core.wsgi --bind 0.0.0.0:8000


  worker_celery:
    build: .
    command: python -m celery -A core worker --loglevel=info

    depends_on:
      - redis
      - backend 
    



